/**
 * GERADO POR `scripts/generate-media.mjs` — não editar à mão.
 *
 * Dimensões e placeholders de blur das imagens em `public/images/`. O blur foi
 * produzido pela mesma função que o Next usa no build, então é idêntico ao que
 * o site servia quando as imagens eram imports estáticos.
 *
 * Quando a biblioteca de mídia do painel entrar, estes valores passam a vir do
 * banco e este arquivo continua servindo apenas ao conteúdo padrão.
 */

export const MEDIA = {
  "cred-diretor-juventude": {
    "url": "/images/cred-diretor-juventude.jpeg",
    "width": 495,
    "height": 619,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//aAAwDAQACEAMQAAAAixN//8QAHRAAAQMFAQAAAAAAAAAAAAAABAECAwASEyEjQf/aAAgBAQABPwAiEYhcsvKYjvaniOc7Vf/EABURAQEAAAAAAAAAAAAAAAAAABEA/9oACAECAQE/AEv/xAAWEQEBAQAAAAAAAAAAAAAAAAABABL/2gAIAQMBAT8AyN//2Q==",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "cred-medalha-jk": {
    "url": "/images/cred-medalha-jk.jpeg",
    "width": 1620,
    "height": 1080,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAFAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAv/aAAwDAQACEAMQAAAAkBT/xAAcEAACAgIDAAAAAAAAAAAAAAACAwERAAQFFmL/2gAIAQEAAT8A7VzpqURbzJNbTIS9TFXn/8QAFhEAAwAAAAAAAAAAAAAAAAAAAAEx/9oACAECAQE/AHT/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AH//2Q==",
    "blurWidth": 8,
    "blurHeight": 5
  },
  "cred-partido-novo": {
    "url": "/images/cred-partido-novo.jpeg",
    "width": 852,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAUDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAT/xAAVAQEBAAAAAAAAAAAAAAAAAAACBP/aAAwDAQACEAMQAAAAhCo//8QAGhAAAwEAAwAAAAAAAAAAAAAAAQIDEQAUgf/aAAgBAQABPwCXSaSvS5DktoDqBnp5/8QAGREAAwADAAAAAAAAAAAAAAAAAQIDACJC/9oACAECAQE/AElMomvIz//EABkRAAMAAwAAAAAAAAAAAAAAAAECAwASMv/aAAgBAwEBPwB60DuNj0c//9k=",
    "blurWidth": 5,
    "blurHeight": 8
  },
  "evento-01": {
    "url": "/images/evento-01.jpeg",
    "width": 1024,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/9oADAMBAAIQAxAAAACSDP8A/8QAHRAAAQIHAAAAAAAAAAAAAAAAAgEDAAQFEiJScf/aAAgBAQABPwCYrTaWoYC5qZ5LyP/EABkRAAIDAQAAAAAAAAAAAAAAAAECABJRcf/aAAgBAgEBPwBQKrzTP//EABgRAAIDAAAAAAAAAAAAAAAAAAABEmGR/9oACAEDAQE/AJOsP//Z",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "evento-02": {
    "url": "/images/evento-02.jpeg",
    "width": 1024,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAUAQEAAAAAAAAAAAAAAAAAAAAD/9oADAMBAAIQAxAAAACKBb//xAAcEAACAgIDAAAAAAAAAAAAAAACBAEDABMhMWH/2gAIAQEAAT8ASdTYUrXgaK9JTyfRexn/xAAWEQEBAQAAAAAAAAAAAAAAAAABAgD/2gAIAQIBAT8AuBp3/8QAFhEBAQEAAAAAAAAAAAAAAAAAAgEA/9oACAEDAQE/AA0TJv/Z",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "evento-03": {
    "url": "/images/evento-03.jpeg",
    "width": 1024,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//aAAwDAQACEAMQAAAAkxJ//8QAHBAAAwABBQAAAAAAAAAAAAAAAQMEAgAUISKB/9oACAEBAAE/ALaI83sUaRtCRmvknt5r/8QAGBEAAgMAAAAAAAAAAAAAAAAAAAECETH/2gAIAQIBAT8AUVS0/8QAGREAAQUAAAAAAAAAAAAAAAAAUQABAhMx/9oACAEDAQE/ALJMNC//2Q==",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "evento-04": {
    "url": "/images/evento-04.jpeg",
    "width": 1024,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/aAAwDAQACEAMQAAAAjBn/xAAcEAACAgIDAAAAAAAAAAAAAAABAwQhAAIFESL/2gAIAQEAAT8Agc1FdHBYAq733afXVUM//8QAFREBAQAAAAAAAAAAAAAAAAAAADH/2gAIAQIBAT8Ar//EABgRAAIDAAAAAAAAAAAAAAAAAAABEVGR/9oACAEDAQE/AIVLD//Z",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "evento-05": {
    "url": "/images/evento-05.jpeg",
    "width": 1024,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAVAQEBAAAAAAAAAAAAAAAAAAAAAv/aAAwDAQACEAMQAAAAixL/xAAcEAACAQUBAAAAAAAAAAAAAAACAwEABAUyQWL/2gAIAQEAAT8AflVqWk5tkEBDp77Nf//EABcRAAMBAAAAAAAAAAAAAAAAAAABAkL/2gAIAQIBAT8AUQso/8QAGBEAAgMAAAAAAAAAAAAAAAAAAAIBETH/2gAIAQMBAT8AhmrT/9k=",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "evento-06": {
    "url": "/images/evento-06.jpeg",
    "width": 1024,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAVAQEBAAAAAAAAAAAAAAAAAAACA//aAAwDAQACEAMQAAAAghJf/8QAHBAAAgICAwAAAAAAAAAAAAAAAhEBAwASBCHR/9oACAEBAAE/ALuRM1A5E7NyXaHT15//xAAWEQEBAQAAAAAAAAAAAAAAAAABABL/2gAIAQIBAT8AyF//xAAWEQEBAQAAAAAAAAAAAAAAAAABABL/2gAIAQMBAT8A0t//2Q==",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "hero-matheus": {
    "url": "/images/hero-matheus.jpg",
    "width": 1600,
    "height": 1075,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAFAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/aAAwDAQACEAMQAAAAlgZ//8QAHBAAAgAHAAAAAAAAAAAAAAAAAQIAAxMUITOC/9oACAEBAAE/ABMWwKUxuGeTH//EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oACAECAQE/AK//xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oACAEDAQE/AH//2Q==",
    "blurWidth": 8,
    "blurHeight": 5
  },
  "quem-matheus": {
    "url": "/images/quem-matheus.jpeg",
    "width": 1024,
    "height": 1280,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAYDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAb/xAAUAQEAAAAAAAAAAAAAAAAAAAAC/9oADAMBAAIQAxAAAACNBf8A/8QAHRAAAQMFAQAAAAAAAAAAAAAAAQMRIQACBRI0Uf/aAAgBAQABPwBfMp7cqdskB5cexX//xAAWEQEBAQAAAAAAAAAAAAAAAAABAAL/2gAIAQIBAT8Acl//xAAXEQADAQAAAAAAAAAAAAAAAAAAAQID/9oACAEDAQE/AFpR/9k=",
    "blurWidth": 6,
    "blurHeight": 8
  },
  "simoes": {
    "url": "/images/simoes.jpeg",
    "width": 900,
    "height": 1600,
    "blurDataURL": "data:image/jpeg;base64,/9j/2wBDAAoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/2wBDAQoKCgoKCgsMDAsPEA4QDxYUExMUFiIYGhgaGCIzICUgICUgMy03LCksNy1RQDg4QFFeT0pPXnFlZXGPiI+7u/v/wgARCAAIAAUDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAX/xAAVAQEBAAAAAAAAAAAAAAAAAAABAv/aAAwDAQACEAMQAAAAliX/xAAcEAABAwUAAAAAAAAAAAAAAAACAAMFAQQRIXH/2gAIAQEAAT8AKXhrMyZYq4Y81lf/xAAXEQEAAwAAAAAAAAAAAAAAAAABABEy/9oACAECAQE/ACgyT//EABcRAQADAAAAAAAAAAAAAAAAAAEAETL/2gAIAQMBAT8AbXTP/9k=",
    "blurWidth": 5,
    "blurHeight": 8
  }
} as const;

export type MediaKey = keyof typeof MEDIA;
